version: '3'

services:
  envoy-tuya:
    image: "envoyproxy/envoy:v1.21.1"
    container_name: envoy
    ports:
     - "443:443"
     - "9901:9901"
    volumes:
      - "./tls:/etc/envoy/tls"
      - "./log:/var/log/envoy"
      - "./sds-source-example.yaml:/root/run/config/envoy.yaml"
    restart: always
    privileged: true

